### PR TITLE
Migrate to Purescript 12

### PR DESCRIPTION
**Pull request by Dretch**

### CODE REVIEW

**Review by icyrockcom — APPROVED** [review]
Great, thank you @Dretch!

**Comment by Dretch** [comment]
Thanks @icyrockcom 

Any chance of a new release? I can then file a pull request in https://github.com/purescript/package-sets so I can use the library with `psc-package`

EDIT: hold that thought - I have some more pull requests incoming!

**Comment by icyrockcom** [comment]
Sure I can release v0.2.0 - let me know if you had any other changes in mind before I do.

**Comment by Dretch** [comment]
@icyrockcom thanks for merging my pull requests. Please could you do a new release now?

**Comment by icyrockcom** [comment]
@Dretch I changed a few minor bits, please see https://github.com/icyrockcom/purescript-cheerio/commit/e8111489db752aafbafe477dbf03a812d183dde7.

Released as v0.2.0 and published to [Pursuit](https://pursuit.purescript.org/packages/purescript-cheerio/0.2.0).

Let me know if you run into any issues.

**Comment by Dretch** [comment]
Great, Thanks @icyrockcom

**Pull request merged**
